# Name of this action
name: autoblack_pull_request

# This action runs only when pull_request to dev
on:
  pull_request:
    branches: [dev]

# Jobs which will be done on this action
jobs:
  # "build" is id of job
  build:
    # Specify os image
    runs-on: ubuntu-latest
    # Steps to be done on this job
    steps:
      # Fetch source cods from github repository
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all branches and all histories
      # Setup python environment
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7.9
      # Install black
      - run: pip install black
      # Find modified files only and check if black is needed
      - run: black --check $(git diff --name-only $(git merge-base --fork-point origin/dev) --diff-filter=d -- '*.py')

      #black --check .
      - name: If needed, commit black changes to the pull request
        shell: bash
        if: failure()
        run: |
          #printenv | grep GITHUB
          git config --global user.name 'bmy4415'
          git config --global user.email 'bmy4415@naver.com'          
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          #git remote -v
          #git branch
          #git status
          # black .
          black $(git diff --name-only $(git merge-base --fork-point origin/dev) --diff-filter=d -- '*.py')
          git status
          #echo DO NOT git checkout $GITHUB_HEAD_REF
          ## git checkout $GITHUB_HEAD_REF
          #echo ready to commit
          git commit -am "fixup! Format Python code with psf/black pull_request"
          #echo ready to push
          # git push

          # Originally, push is not feasible from pull request 
          git push --force origin HEAD:$GITHUB_REF
          # remote: Permission to cclauss/autoblack.git denied to github-actions[bot].
          # fatal: unable to access 'https://github.com/cclauss/autoblack/': The requested URL returned error: 403
          # https://github.com/cclauss/autoblack/pull/9
          # https://github.com/elephantworks/autoblack/edit/patch-1/platform_info.py?pr=%2Fcclauss%2Fautoblack%2Fpull%2F9
          # error: Your local changes to the following files would be overwritten by checkout:
          # platform_info.py
          # Please commit your changes or stash them before you switch branches.
          # Aborting
          # git checkout patch-1
        #git remote -v || true
        #git branch || true
        #echo "A"
        #git remote add locala ***github.com/${GITHUB_ACTOR}/autoblack || true
        #echo "B"
        #git remote add localb github.com/${GITHUB_ACTOR}/autoblack || true
        #echo "C"
        #git remote add localc git@github.com/${GITHUB_ACTOR}/autoblack.git || true
        #echo "D"
        #git remote add locald https://github.com/${GITHUB_ACTOR}/autoblack || true
        #echo "E"
        #git remote -v || true
        #git branch || true
        #echo "F"
        ##git push locala || true
        #git push locala HEAD:${GITHUB_REF:5} || true
        #echo "G"
        ##git push locald || true
        #git push locald HEAD:${GITHUB_REF:5} || true
        ## git push origin HEAD:${GITHUB_REF:5}
        #echo "H"
        ## git push
        #git remote -v || true
        #git branch || true
