# Name of this action
name: autoblack_pull_request

# This action runs only when pull_request to dev
on:
  pull_request:
    branches: [dev]

# Jobs which will be done on this action
jobs:
  # "build" is id of job
  build:
    # Specify os image
    runs-on: ubuntu-latest
    # Steps to be done on this job
    steps:
      # Fetch source cods from github repository
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Setup python environment
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7.9
      # # Install black
      # - run: pip install black
      # # Find modified files only and check if black is needed
      # - run: black --check $(git diff --name-only $(git merge-base --fork-point origin/dev) --diff-filter=d -- '*.py')

      #black --check .
      - name: Do black formatting
        shell: bash
        run: |
          git checkout ${{ github.head_ref }}  # checkout to pull-request source branch
          pip install black
          git config --global user.name 'bmy4415'
          git config --global user.email 'bmy4415@naver.com'
          # git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          #git remote -v
          #git branch
          #git status
          # black .
          echo "NOW DO BLACK FORMATTING"
          black $(git diff --name-only $(git merge-base --fork-point ${{ github.base_ref }}) --diff-filter=d -- '*.py')
          echo "BLACK FORMATTING IS DONE"
          # git log
          # echo "END OF GIT LOG"
          git status
          #echo DO NOT git checkout $GITHUB_HEAD_REF
          ## git checkout $GITHUB_HEAD_REF
          #echo ready to commit
          echo "$ git add ."
          git add .

          echo "do commit"
          git commit -am "fixup! Format Python code with psf/black pull_request"

          echo "do push"
          git push

          # Originally, push is not feasible from pull request 
          # git push --force origin HEAD:$GITHUB_REF
